import type { GeometryDocument } from "../src/types/geometry";

/** A tiny, hand-built, schema-valid geometry document for fast unit tests. */
export function makeTestGeometry(): GeometryDocument {
  return {
    schema_version: "0.1.0",
    pattern_fingerprint: "test-pattern-fp",
    graph_fingerprint: "test-graph-fp",
    geometry_fingerprint: "test-geometry-fp",
    units: "cm",
    gauge: { stitches_per_cm: 1.6, rounds_per_cm: 1.2, yarn_diameter_cm: 0.3 },
    stitches: [
      {
        stitch_id: "crown-r01-s000",
        component_id: "crown",
        stitch_type: "hdc",
        round_index: 1,
        sequence_index: 0,
        position: [0, 0, 0],
        orientation: [0, 0, 0, 1],
        tangent: [1, 0, 0],
        normal: [0, 1, 0],
        binormal: [0, 0, 1],
        scale: 1,
        loop_placement: "both",
        colour_id: "main",
        yarn_id: "main",
        parent_stitch_ids: [],
        is_increase: false,
        is_decrease: false,
        source_reference: "crown round 1 operation 1",
      },
      {
        stitch_id: "crown-r02-s000",
        component_id: "crown",
        stitch_type: "hdc",
        round_index: 2,
        sequence_index: 1,
        position: [1, 0, 0.5],
        orientation: [0, 0, 0, 1],
        tangent: [0, 1, 0],
        normal: [1, 0, 0],
        binormal: [0, 0, 1],
        scale: 1,
        loop_placement: "both",
        colour_id: "main",
        yarn_id: "main",
        parent_stitch_ids: ["crown-r01-s000"],
        is_increase: true,
        is_decrease: false,
        source_reference: "crown round 2 operation 1 (repeat 1/8)",
      },
      {
        stitch_id: "body-r10-s000",
        component_id: "body",
        stitch_type: "hdc",
        round_index: 10,
        sequence_index: 2,
        position: [2, 0, -3],
        orientation: [0, 0, 0, 1],
        tangent: [0, 1, 0],
        normal: [1, 0, 0],
        binormal: [0, 0, 1],
        scale: 1,
        loop_placement: "both",
        colour_id: "main",
        yarn_id: "main",
        parent_stitch_ids: ["crown-r02-s000"],
        is_increase: false,
        is_decrease: false,
        source_reference: "body round 10 operation 1",
      },
    ],
    yarn_segments: [
      {
        segment_id: "seg-1",
        owning_stitch_id: "crown-r02-s000",
        from_stitch_id: "crown-r01-s000",
        to_stitch_id: "crown-r02-s000",
        control_points: [
          [0, 0, 0],
          [1, 0, 0.5],
        ],
        radius_cm: 0.15,
        segment_type: "connector",
      },
      {
        segment_id: "seg-2",
        owning_stitch_id: "body-r10-s000",
        from_stitch_id: "crown-r02-s000",
        to_stitch_id: "body-r10-s000",
        control_points: [
          [1, 0, 0.5],
          [2, 0, -3],
        ],
        radius_cm: 0.15,
        segment_type: "connector",
      },
    ],
    edges: [
      { edge_id: "e1", edge_type: "insertion", source_id: "crown-r02-s000", target_id: "crown-r01-s000" },
    ],
    bounds: { min: [0, 0, -3], max: [2, 0, 0.5] },
    measurements: { overall_height_cm: 3.5, max_radius_cm: 2, max_circumference_cm: 12.57 },
    warnings: ["test warning"],
  };
}
