"""initial portal schema

Revision ID: f162ca520de8
Revises:
Create Date: 2026-07-22 14:12:25.482057

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f162ca520de8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=300), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_admin_users_username"), "admin_users", ["username"], unique=True)
    op.create_table(
        "invitations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=False),
        sa.Column("used_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invitations_token_hash"), "invitations", ["token_hash"], unique=True)
    op.create_table(
        "contributors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invitation_id", sa.Integer(), nullable=False),
        sa.Column("display_identifier", sa.String(length=200), nullable=False),
        sa.Column("contact_email", sa.String(length=320), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invitation_id"],
            ["invitations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "crochet_projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contributor_id", sa.Integer(), nullable=False),
        sa.Column("submission_reference", sa.String(length=16), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "UNDER_REVIEW",
                "CHANGES_REQUESTED",
                "REJECTED",
                "APPROVED",
                "WITHDRAWN",
                name="projectstatus",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("name_or_description", sa.String(length=300), nullable=True),
        sa.Column(
            "craft_type",
            sa.Enum(
                "CROCHET", "KNITTING", "UNKNOWN", name="crafttype", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column(
            "project_category",
            sa.Enum(
                "BEANIE",
                "STITCH_SWATCH",
                "OTHER",
                name="projectcategory",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column(
            "made_by_contributor",
            sa.Enum("YES", "NO", "UNKNOWN", name="tristate", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column(
            "used_existing_pattern",
            sa.Enum("YES", "NO", "UNKNOWN", name="tristate", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column(
            "pattern_owned_by_contributor",
            sa.Enum("YES", "NO", "UNKNOWN", name="tristate", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column(
            "construction_direction",
            sa.Enum(
                "TOP_DOWN",
                "BOTTOM_UP",
                "UNKNOWN",
                name="constructiondirection",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "worked_in",
            sa.Enum("ROWS", "ROUNDS", "UNKNOWN", name="workedin", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column(
            "round_style",
            sa.Enum("CONTINUOUS", "JOINED", "UNKNOWN", name="roundstyle", native_enum=False),
            nullable=False,
        ),
        sa.Column("stitch_families", sa.JSON(), nullable=False),
        sa.Column("component_notes", sa.Text(), nullable=True),
        sa.Column("free_text_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contributor_id"],
            ["contributors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_crochet_projects_status"), "crochet_projects", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_crochet_projects_submission_reference"),
        "crochet_projects",
        ["submission_reference"],
        unique=True,
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("contributor_id", sa.Integer(), nullable=True),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contributor_id"],
            ["contributors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["crochet_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "consent_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("contributor_provided_identifier", sa.String(length=200), nullable=False),
        sa.Column("consent_version", sa.String(length=20), nullable=False),
        sa.Column("consented_at", sa.DateTime(), nullable=False),
        sa.Column("owns_photographs", sa.Boolean(), nullable=False),
        sa.Column("research_evaluation_use", sa.Boolean(), nullable=False),
        sa.Column("product_development_use", sa.Boolean(), nullable=False),
        sa.Column("model_training_use", sa.Boolean(), nullable=False),
        sa.Column("public_demonstration_use", sa.Boolean(), nullable=False),
        sa.Column("contact_for_missing_details", sa.Boolean(), nullable=False),
        sa.Column("privacy_notice_accepted", sa.Boolean(), nullable=False),
        sa.Column(
            "attribution_preference",
            sa.Enum(
                "FULL_NAME",
                "HANDLE_OR_FIRST_NAME",
                "ANONYMOUS",
                name="attributionpreference",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("attribution_text", sa.String(length=200), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["crochet_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
    )
    op.create_table(
        "physical_trial_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("trial_id", sa.String(length=20), nullable=False),
        sa.Column("pattern_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("physical_result_id", sa.String(length=100), nullable=True),
        sa.Column("validated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["crochet_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "image_type",
            sa.Enum(
                "FRONT",
                "CROWN_TOP",
                "STITCH_MACRO",
                "SIDE",
                "INTERIOR",
                "BRIM",
                "SEAM_JOIN",
                "SCALE_REFERENCE",
                "SWATCH_FULL",
                "SWATCH_FRONT_MACRO",
                "SWATCH_EDGE",
                "OTHER",
                name="imagetype",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("stored_filename", sa.String(length=80), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("image_format", sa.String(length=10), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("duplicate_of_image_id", sa.Integer(), nullable=True),
        sa.Column("exif_stripped", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["duplicate_of_image_id"],
            ["project_images.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["crochet_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stored_filename", name="uq_project_images_stored_filename"),
    )
    op.create_index(op.f("ix_project_images_sha256"), "project_images", ["sha256"], unique=False)
    op.create_table(
        "project_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("yarn_brand", sa.String(length=200), nullable=True),
        sa.Column("yarn_name", sa.String(length=200), nullable=True),
        sa.Column("fibre", sa.String(length=200), nullable=True),
        sa.Column("yarn_weight", sa.String(length=50), nullable=True),
        sa.Column("colour", sa.String(length=100), nullable=True),
        sa.Column("hook_mm", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("strands_held", sa.Integer(), nullable=True),
        sa.Column("substitutions_made", sa.Boolean(), nullable=True),
        sa.Column("materials_notes", sa.Text(), nullable=True),
        sa.Column("stitches_per_10cm", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("rounds_per_10cm", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "gauge_blocking_state",
            sa.Enum(
                "BEFORE_BLOCKING",
                "AFTER_BLOCKING",
                "UNKNOWN",
                name="gaugeblockingstate",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("relaxed_circumference_cm", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("stretched_circumference_cm", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("total_height_cm", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("crown_diameter_cm", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("brim_height_cm", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("swatch_flat_width_cm", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("swatch_flat_height_cm", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("measurement_notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["crochet_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
    )
    op.create_table(
        "review_decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("admin_id", sa.Integer(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum(
                "APPROVE",
                "REJECT",
                "CHANGES_REQUESTED",
                "NOTE",
                name="reviewdecisiontype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "verified_craft_type",
            sa.Enum(
                "CROCHET", "KNITTING", "UNKNOWN", name="crafttype", native_enum=False, length=20
            ),
            nullable=True,
        ),
        sa.Column(
            "verified_project_category",
            sa.Enum(
                "BEANIE",
                "STITCH_SWATCH",
                "OTHER",
                name="projectcategory",
                native_enum=False,
                length=30,
            ),
            nullable=True,
        ),
        sa.Column("verified_stitch_labels", sa.JSON(), nullable=True),
        sa.Column("allowed_uses", sa.JSON(), nullable=True),
        sa.Column(
            "data_quality_status",
            sa.Enum(
                "OK",
                "NEEDS_REVIEW",
                "EXCLUDED",
                name="dataqualitystatus",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("exclusion_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["admin_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["crochet_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review_decisions")
    op.drop_table("project_metadata")
    op.drop_index(op.f("ix_project_images_sha256"), table_name="project_images")
    op.drop_table("project_images")
    op.drop_table("physical_trial_links")
    op.drop_table("consent_records")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_crochet_projects_submission_reference"), table_name="crochet_projects")
    op.drop_index(op.f("ix_crochet_projects_status"), table_name="crochet_projects")
    op.drop_table("crochet_projects")
    op.drop_table("contributors")
    op.drop_index(op.f("ix_invitations_token_hash"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_index(op.f("ix_admin_users_username"), table_name="admin_users")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
